//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.01 at 02:06:27 PM IST 
//


package com.gl.platform.web.rest;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.gl.platform.jaxb.trex.v118.AcademicSessionType;
import com.gl.platform.jaxb.trex.v118.AcademicStatusType;
import com.gl.platform.jaxb.trex.v118.AcademicSummaryType;
import com.gl.platform.jaxb.trex.v118.AddressType;
import com.gl.platform.jaxb.trex.v118.AssessmentSubTestType;
import com.gl.platform.jaxb.trex.v118.AssessmentType;
import com.gl.platform.jaxb.trex.v118.AttendanceType;
import com.gl.platform.jaxb.trex.v118.CourseType;
import com.gl.platform.jaxb.trex.v118.CurrentCourseworkType;
import com.gl.platform.jaxb.trex.v118.DisciplineActionType;
import com.gl.platform.jaxb.trex.v118.DistinguishedAchievementType;
import com.gl.platform.jaxb.trex.v118.DualLanguageImmersionType;
import com.gl.platform.jaxb.trex.v118.EnrollmentType;
import com.gl.platform.jaxb.trex.v118.EthnicityType;
import com.gl.platform.jaxb.trex.v118.ImmunizationType;
import com.gl.platform.jaxb.trex.v118.ParentType;
import com.gl.platform.jaxb.trex.v118.PerfAckApIbType;
import com.gl.platform.jaxb.trex.v118.PerfAckBilingBilitType;
import com.gl.platform.jaxb.trex.v118.PerfAckCertLicType;
import com.gl.platform.jaxb.trex.v118.PerfAckCollegeAssessType;
import com.gl.platform.jaxb.trex.v118.PerfAckDualCreditType;
import com.gl.platform.jaxb.trex.v118.PersonNameType;
import com.gl.platform.jaxb.trex.v118.SchoolType;
import com.gl.platform.jaxb.trex.v118.SpecialProgramsType;
import com.gl.platform.jaxb.trex.v118.StudentDemographicType;
import com.gl.platform.jaxb.trex.v118.StudentIdentificationType;
import com.gl.platform.jaxb.trex.v118.StudentRecordType;
import com.gl.platform.jaxb.trex.v118.StudentRecordsType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.parsed.objects package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TRExStudentRecords_QNAME = new QName("urn:us:tx:state:tea:TREx:v1.18", "TRExStudentRecords");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.parsed.objects
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StudentRecordsType }
     * 
     */
    public StudentRecordsType createStudentRecordsType() {
        return new StudentRecordsType();
    }

    /**
     * Create an instance of {@link ImmunizationType }
     * 
     */
    public ImmunizationType createImmunizationType() {
        return new ImmunizationType();
    }

    /**
     * Create an instance of {@link PerfAckCollegeAssessType }
     * 
     */
    public PerfAckCollegeAssessType createPerfAckCollegeAssessType() {
        return new PerfAckCollegeAssessType();
    }

    /**
     * Create an instance of {@link StudentDemographicType }
     * 
     */
    public StudentDemographicType createStudentDemographicType() {
        return new StudentDemographicType();
    }

    /**
     * Create an instance of {@link SpecialProgramsType }
     * 
     */
    public SpecialProgramsType createSpecialProgramsType() {
        return new SpecialProgramsType();
    }

    /**
     * Create an instance of {@link PerfAckBilingBilitType }
     * 
     */
    public PerfAckBilingBilitType createPerfAckBilingBilitType() {
        return new PerfAckBilingBilitType();
    }

    /**
     * Create an instance of {@link DualLanguageImmersionType }
     * 
     */
    public DualLanguageImmersionType createDualLanguageImmersionType() {
        return new DualLanguageImmersionType();
    }

    /**
     * Create an instance of {@link ParentType }
     * 
     */
    public ParentType createParentType() {
        return new ParentType();
    }

    /**
     * Create an instance of {@link StudentIdentificationType }
     * 
     */
    public StudentIdentificationType createStudentIdentificationType() {
        return new StudentIdentificationType();
    }

    /**
     * Create an instance of {@link AcademicStatusType }
     * 
     */
    public AcademicStatusType createAcademicStatusType() {
        return new AcademicStatusType();
    }

    /**
     * Create an instance of {@link CurrentCourseworkType }
     * 
     */
    public CurrentCourseworkType createCurrentCourseworkType() {
        return new CurrentCourseworkType();
    }

    /**
     * Create an instance of {@link EnrollmentType }
     * 
     */
    public EnrollmentType createEnrollmentType() {
        return new EnrollmentType();
    }

    /**
     * Create an instance of {@link CourseType }
     * 
     */
    public CourseType createCourseType() {
        return new CourseType();
    }

    /**
     * Create an instance of {@link PersonNameType }
     * 
     */
    public PersonNameType createPersonNameType() {
        return new PersonNameType();
    }

    /**
     * Create an instance of {@link DistinguishedAchievementType }
     * 
     */
    public DistinguishedAchievementType createDistinguishedAchievementType() {
        return new DistinguishedAchievementType();
    }

    /**
     * Create an instance of {@link AttendanceType }
     * 
     */
    public AttendanceType createAttendanceType() {
        return new AttendanceType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link AssessmentSubTestType }
     * 
     */
    public AssessmentSubTestType createAssessmentSubTestType() {
        return new AssessmentSubTestType();
    }

    /**
     * Create an instance of {@link PerfAckCertLicType }
     * 
     */
    public PerfAckCertLicType createPerfAckCertLicType() {
        return new PerfAckCertLicType();
    }

    /**
     * Create an instance of {@link AcademicSummaryType }
     * 
     */
    public AcademicSummaryType createAcademicSummaryType() {
        return new AcademicSummaryType();
    }

    /**
     * Create an instance of {@link EthnicityType }
     * 
     */
    public EthnicityType createEthnicityType() {
        return new EthnicityType();
    }

    /**
     * Create an instance of {@link PerfAckApIbType }
     * 
     */
    public PerfAckApIbType createPerfAckApIbType() {
        return new PerfAckApIbType();
    }

    /**
     * Create an instance of {@link DisciplineActionType }
     * 
     */
    public DisciplineActionType createDisciplineActionType() {
        return new DisciplineActionType();
    }

    /**
     * Create an instance of {@link AcademicSessionType }
     * 
     */
    public AcademicSessionType createAcademicSessionType() {
        return new AcademicSessionType();
    }

    /**
     * Create an instance of {@link AssessmentType }
     * 
     */
    public AssessmentType createAssessmentType() {
        return new AssessmentType();
    }

    /**
     * Create an instance of {@link PerfAckDualCreditType }
     * 
     */
    public PerfAckDualCreditType createPerfAckDualCreditType() {
        return new PerfAckDualCreditType();
    }

    /**
     * Create an instance of {@link SchoolType }
     * 
     */
    public SchoolType createSchoolType() {
        return new SchoolType();
    }

    /**
     * Create an instance of {@link StudentRecordType }
     * 
     */
    public StudentRecordType createStudentRecordType() {
        return new StudentRecordType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StudentRecordsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:tx:state:tea:TREx:v1.18", name = "TRExStudentRecords")
    public JAXBElement<StudentRecordsType> createTRExStudentRecords(StudentRecordsType value) {
        return new JAXBElement<StudentRecordsType>(_TRExStudentRecords_QNAME, StudentRecordsType.class, null, value);
    }

}
